Add N5193A lan streaming example
morgan-at-keysight/pyarbtools pull request #28
Opened 2021-01-15 17:19 UTC by jeff-at-keysight

requirements.txt:
 removed non-run time requirements to simplify install
  
pdwBuilder.py:
 analog_bin_pdw_file_builder() - separated raw pdw section and end block for mode intuitive block separation
  
instruments.py:
 AnalogUXG():
  added bin_raw_pdw_block_builder() to build raw pdws without headers for direct lan streaming
  
examples.py:
 added analog_uxg_lan_stream_pdw_example() for direct lan streaming
 
 renamed analog_uxg_file_stream_pdw_example - added file to name to distinguish from lan streaming

2021-01-20 01:08 UTC, morgan-at-keysight commented on README.rst
> +*Current version: 2021.01.15*
Version should be `2021.01.1`. I have been breaking the versions down by month. So `2021.01.1` would be the first update in Jan 2021.

2021-01-20 01:09 UTC, morgan-at-keysight requested changes
@jeff-at-keysight these are all great changes. The only thing that needs attention is the version. There's a little comment there that explains it.

2021-01-20 11:18 UTC, jeff-at-keysight commented
I just reviewed and confirmed.

Thanks,

Jeff

From: morgan-at-keysight <notifications@github.com>
Sent: Tuesday, January 19, 2021 8:09 PM
To: morgan-at-keysight/pyarbtools <pyarbtools@noreply.github.com>
Cc: Jeff Murphy <jeff_murphy@keysight.com>; Mention <mention@noreply.github.com>
Subject: Re: [morgan-at-keysight/pyarbtools] Add N5193A lan streaming example (#28)


[EXTERNAL]

@morgan-at-keysight requested changes on this pull request.

@jeff-at-keysight<https://urldefense.com/v3/__https:/github.com/jeff-at-keysight__;!!I5pVk4LIGAfnvw!yA3szppEthCMkqxFnhd2OR_Gt7ME61kswLlns6h-w2RnnN-_65GsHEz_V9vH$> these are all great changes. The only thing that needs attention is the version. There's a little comment there that explains it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/morgan-at-keysight/pyarbtools/pull/28*pullrequestreview-571792043__;Iw!!I5pVk4LIGAfnvw!yA3szppEthCMkqxFnhd2OR_Gt7ME61kswLlns6h-w2RnnN-_65GsHGMCQL8C$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/API7PZQUW2SFR2ZRGIUTEGTS2YUMNANCNFSM4WELMVAA__;!!I5pVk4LIGAfnvw!yA3szppEthCMkqxFnhd2OR_Gt7ME61kswLlns6h-w2RnnN-_65GsHFbEaUwV$>.

2021-01-21 00:11 UTC, morgan-at-keysight commented
@jeff-at-keysight if you've updated the code, can you add another commit to this pull request with the changes you made?

2021-01-21 00:43 UTC, merged